-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("mako")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME QT_QPA_PLATFORM QT_QUICK_CONTROLS_STYLE XCURSOR_THEME XCURSOR_SIZE GTK_THEME")
    hl.exec_cmd("systemctl --user import-environment GTK_THEME QT_QPA_PLATFORMTHEME QT_QUICK_CONTROLS_STYLE 2>/dev/null || true")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/apply-desktop-theme.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/launch-kdeconnect.sh")
    hl.exec_cmd("hyprctl setcursor Oxygen_White 24")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/waybar/launch.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/conky/Atria/start.sh")
end)

hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Oxygen_White")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QUICK_CONTROLS_STYLE", "org.kde.breeze")
hl.env("GTK_THEME", "Adwaita")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
