background {
    monitor =
    path = /home/syds/Downloads/bg.jpg
    color = rgba(160, 231, 205, 0.15)
    blur_passes = 2
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.85
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 500, 50
    outline_thickness = 0
    dots_size = 0.33
    dots_spacing = 0.2
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(84, 157, 108, 0.35)
    inner_color = rgba(242, 247, 244, 0.55)
    font_color = rgb(42, 63, 54)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i></i>
    hide_input = false
    rounding = 12
    check_color = rgb(84, 157, 108)
    fail_color = rgb(176, 84, 84)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    text_align = center
    color = #2A3F36
    font_size = 60
    font_family = Jost
    rotate = 0

    position = 0, 100
    halign = center
    valign = center
}
